// Crop pixel art for the garden plots (14x14, the bottom rows are the soil).
import type { PixelGrid } from "@/components/ui/PixelArt";
import type { CropKind } from "./farm";

export const CROP_ART: Record<Exclude<CropKind, "empty">, PixelGrid> = {
  seed: [
    "..............",
    "..............",
    "..............",
    "......y.......",
    ".....yYy......",
    "......y.......",
    "..............",
    "..............",
    "..............",
    "......oo......",
    ".....okko.....",
    "......oo......",
    "..............",
    "..............",
  ],
  quiet: [
    "..............",
    "..........ooo.",
    "...........o..",
    "..........ooo.",
    "....yyy.......",
    "...yyY...oo...",
    "..yyY.....o...",
    "..yyY....oo...",
    "..yyY.........",
    "...yyY........",
    "....yyy.......",
    "..............",
    "..............",
    "..............",
  ],
  thirsty: [
    "..............",
    "..............",
    "..............",
    "..............",
    "..........b...",
    ".........bBb..",
    "......o..bbb..",
    ".....oko......",
    "....okkgo.....",
    "......go......",
    "......go......",
    ".....ogGo.....",
    "..............",
    "..............",
  ],
  soggy: [
    "..............",
    "..............",
    "..............",
    "..............",
    "....oo..oo....",
    "...ognoongo...",
    "....oggGgo....",
    "......go......",
    "......go......",
    "......Go......",
    "..bBbbbbbBb...",
    ".bbBbbbbBbbb..",
    "..bbbbbbbbb...",
    "..............",
  ],
  parsnip: [
    "..............",
    "..............",
    ".....oo.oo....",
    "....ogg.ggo...",
    "....ognogGo...",
    ".....ogggo....",
    "......ogo.....",
    ".....occco....",
    "....occwcCo...",
    "....occccCo...",
    ".....occCo....",
    "......oCo.....",
    ".......o......",
    "..............",
  ],
  pumpkin: [
    "..............",
    "......oo......",
    ".....oGgo.....",
    "......oo.gg...",
    "...oooooooGg..",
    "..orrRrrRrro..",
    ".orrwRrrRrrro.",
    ".orrrRrrRrrRo.",
    ".orrrRrrRrrRo.",
    ".orrrRrrRrRRo.",
    "..oRRRRRRRRo..",
    "...oooooooo...",
    "..............",
    "..............",
  ],
  stardrop: [
    "......o.......",
    ".....oyo......",
    "..oooyyyooo...",
    "..oyyywyyyo...",
    "...oyyyyyo....",
    "...oyyoyyo....",
    "..oyo.go.oyo..",
    "......go......",
    "...oo.go.oo...",
    "..ognogoongo..",
    "...ogggggo....",
    "......go......",
    "......Go......",
    "..............",
  ],
};

export const CROP_LABEL: Record<CropKind, string> = {
  empty: "Resting soil",
  seed: "Today's seed, waiting for a log",
  quiet: "Quiet day (no movement, still counts!)",
  thirsty: "Thirsty sprout (a bit dry)",
  soggy: "Soggy sprout (a bit rainy)",
  parsnip: "Parsnip (healthy day!)",
  pumpkin: "Pumpkin (3+ day streak!)",
  stardrop: "Stardrop flower (7+ day streak!)",
};
